version: "3.9"

services:
  proxy:
    container_name: nginx_proxy
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html


